config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through',
      to: 'notifications#link_through', as: :link_through
  patch "/request",    to: "books#request"
  get 'notifications', to: 'notifications#index'
  get "information",to: "books#information"
  get "search",     to: "books#search"
  patch "/read",     to: "books#read"
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',    to: 'static_pages#about'
  get  '/signup',   to: 'users#new'
  get  '/welcome',  to: 'users#welcome'
  get  '/home',     to: 'users#home'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :books, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notified_by, class_name: 'User'
  belongs_to :book_id
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @notifications = current_user.notifications
  end

  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
     redirect_to user.find(params[:id])
    end
    user = @noticication.user
    book = user.books.find(@notification.book_id)
    book.reader_id = @notification.notified_by.id
    book.save
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
 <% book = user.books.find(notification.book_id) %>
 <%= link_to "#{notification.notified_by.username}さんが#{book}を読みたいと言っています", link_through_path(notification) %>
</li>

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" id='dropdownMenu1' aria-haspopup="true"
    aria-expanded="true">
    <%= current_user.notifications.where(read: false).count %>
    <span class="glyphicon glyphicon-flag"><i class="fa fa-bell" aria-hidden="true"></i>通知</span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li class="dropdown-header text-center">Notifications</li>
    <%= render current_user.notifications.where(read: false).order('created_at DESC').last(5) %>
    <li class="divider" role="separator"> </li>
    <li class="text-center">
      <%= link_to '通知一覧を見る', notifications_path %>
    </li>
  </ul>
</div>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>