config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through',
      to: 'notifications#link_through', as: :link_through
  patch "/request",    to: "books#request"
  get 'notifications', to: 'notifications#index'
  get "information",to: "books#information"
  get "search",     to: "books#search"
  patch "/read",     to: "books#read"
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',    to: 'static_pages#about'
  get  '/signup',   to: 'users#new'
  get  '/welcome',  to: 'users#welcome'
  get  '/home',     to: 'users#home'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :books, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_shelf.html.erb
<div id="shelf">
  <table class="shelf">
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>
            <a href="#" data-toggle="modal" data-target="#myModal-<%= book.id %>">
              <% if book.reader_id == nil %>
              <%= image_tag book.picture, :height => "200", :alt => book.title %>
              <% else %>
              <%= image_tag book.picture, :height => "200", :alt => book.title, class: "read_book" %>
              <% end %>
            </a>
            <div class="modal fade" id="myModal-<%= book.id %>">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h3><%= book.title %></h3>
                    <h4><%= link_to "#{book.author}", search_url(author: book.author) %></h4>
                    <% if book.reader_id == nil %>
                    <%= image_tag book.picture, :height => "200", :alt => book.title %>
                    <% else %>
                    <%= image_tag book.picture, :height => "200", :alt => book.title, class: "read_book" %>
                    <% end %>
                  </div>
                  <% if current_user?(book.user) %>
                    <div class="modal-body">
                      <% if book.reader_id? %>
                        <% book_reader = User.find(book.reader_id) %>
                        <% if current_user?(book_reader) %>
                          <%= link_to "読書中", read_path(id: @user.id, book_id: book.id, reader_id: current_user.id), class: "btn btn-info", method: :patch %>
                        <% else %>
                          <%= "#{book_reader.name} が読書中です" %>
                        <% end %>
                      <% else %>
                        <%= link_to "読む", read_path(id: @user.id, book_id: book.id, reader_id: current_user.id), class: "btn btn-info", method: :patch %>
                      <% end %>
                      <p><a href="">５人</a>が所有しています</p>
                      <p>読みたい人が<a href="">３人</a>います</p>
                      <p>レビュー</p>
                      <p>メモ</p>
                    </div>
                    <div class="modal-footer">
                      <%= link_to "本棚から消去", book, method: :delete, data: { confirm: "本当に消去しますか？" } %>
                    </div>
                  <% else %>
                    <div class="modal-body">
                      <% if book.reader_id == nil %>
                        <%= link_to "#{@user.name}に貸出リクエストを送る",
                            request_path(id: @user.id, book_id: book.id, reader_id: current_user.id), class: "btn btn-info", method: :patch %>
                      <% else %>
                        <% book_reader = User.find(book.reader_id) %>
                        <% if book_reader == current_user %>
                        <%= link_to "返却", request_path(id: @user.id, book_id: book.id, reader_id: current_user.id), class: "btn btn-info", method: :patch %>
                        <% else %>
                        <%= "#{book_reader.name} が読書中です" %>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>