config/routes.rb
Rails.application.routes.draw do
  get 'notifications/:id/link_through',
      to: 'notifications#link_through', as: :link_through
  patch "/request",    to: "books#request"
  get 'notifications', to: 'notifications#index'
  get "information",to: "books#information"
  get "search",     to: "books#search"
  patch "/read",     to: "books#read"
  get 'sessions/new'
  root 'static_pages#home'
  get  '/about',    to: 'static_pages#about'
  get  '/signup',   to: 'users#new'
  get  '/welcome',  to: 'users#welcome'
  get  '/home',     to: 'users#home'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :books, only: [:create, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer-logo">OurShelf</div>
  <div id="footer-list">
    <!--<h4>MENU</h4>-->
    <ul>
      <li><%= link_to "OurShelfについて", about_path %></li>
      <li><%= link_to "コンセプト", "#" %></li>
      <li><%= link_to "お問い合わせ", "https://twitter.com/ShiDareZAKURA18" %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to "OurShelf", root_path, id: "logo" %></h1>
  <nav>
      <ul class="info">
        <li><%= link_to "ランキング", "#" %></li>
        <li><%= link_to "新着情報", "#" %></li>
      </ul>

      <ul class="navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag current_user.picture.url, :size =>'60' %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "本を探す", search_path %></li>
              <li><%= link_to "ユーザーを探す", users_path %></li>
              <li><%= render 'notifications/notification_dropdown' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="selected"><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
  </nav>
  <div class="clear"></div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <% if logged_in? %>
    <div class="container">
      <%= yield %>
      <%= render  'layouts/footer' %>
    </div>
    <% else %>
      <%= yield %>
      <%= render  'layouts/footer' %>
    <% end %>
  </body>
</html>